# Generated by Django 5.0.6 on 2024-06-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_followercount_followerscount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='FollowerCount',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profileimages'),
        ),
    ]
